Feature/net 7 minimal api
aws-samples/serverless-dotnet-demo pull request #13
Opened 2022-12-09 15:49 UTC by jeastham1993

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-12-09 18:49 UTC, Beau-Gosse-dev requested changes
I like the disclaimer that asp.net isn't fully supported. We should make sure to communicate that.

2022-12-10 11:07 UTC, jeastham1993 commented on src/NET7NativeMinimalAPI/ApiBootstrap/Function.cs
> +    app.Logger.LogInformation("Received request to list all products");
The other samples use the context.Logger object for logging, which we don't have access to here. I'm just using the built in ASP.NET logger.

2022-12-10 11:36 UTC, jeastham1993 commented on src/NET7NativeMinimalAPI/ApiBootstrap/ApiBootstrap.csproj
> +    <TrimMode>partial</TrimMode>
Updated to use TrimMode full alongisde TrimmerRootAssembly.

2022-12-10 11:36 UTC, jeastham1993 commented on src/NET7NativeMinimalAPI/ApiBootstrap/Function.cs
> +    await context.Response.WriteAsJsonAsync(products);
No, I don't believe it does. I think TrimMode partial was cirumcventing it. I've updated to explicitly use the custom serializer.

2022-12-11 21:51 UTC, merged